version: '3.8'

services:
  # Neo4j Vector Database
  neo4j:
    image: neo4j:ubi9
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      # Enable vector search capabilities
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - rag-network

  # Main RAG Application
  app:
    build: .
    container_name: rag-app
    ports:
      - "8501:8501"  # Streamlit
    env_file:
      - .env
    depends_on:
      - neo4j
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - rag-network
    environment:
      - NEO4J_URI=bolt://neo4j:7687

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  rag-network:
    driver: bridge